import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy - Provenix',
  description: 'Provenix Privacy Policy - How we collect, use, and protect your data.',
}

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold text-neutral-900 mb-4">Privacy Policy</h1>
        <p className="text-neutral-600 mb-8">Effective Date: 1 December 2025</p>

        <div className="prose prose-neutral max-w-none space-y-8">
          {/* Definitions */}
          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">1. Definitions</h2>
            <div className="text-neutral-600 space-y-2">
              <p><strong>"Provenix," "we," "us,"</strong> refers to Provenix Pty Ltd, ABN [pending], registered in Western Australia.</p>
              <p><strong>"Service"</strong> refers to the Provenix API, SDK, dashboard, and related services.</p>
              <p><strong>"User," "you,"</strong> refers to individuals or entities using the Service.</p>
              <p><strong>"Personal Data"</strong> refers to information that identifies or can identify an individual.</p>
              <p><strong>"Manifest"</strong> refers to the signed cryptographic metadata generated by the Service.</p>
            </div>
          </section>

          {/* Information We Collect */}
          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">2. Information We Collect</h2>
            <div className="text-neutral-600 space-y-3">
              <h3 className="text-lg font-semibold text-neutral-900">2.1 Account Information</h3>
              <p>When you create an account, we collect:</p>
              <ul className="list-disc list-inside space-y-1 ml-4">
                <li>Email address (required)</li>
                <li>Password (hashed using bcrypt, never stored in plain text)</li>
                <li>Account creation timestamp</li>
                <li>API keys generated (hashed, not reversible)</li>
              </ul>

              <h3 className="text-lg font-semibold text-neutral-900 mt-4">2.2 API Usage Data</h3>
              <p>We log metadata about API calls:</p>
              <ul className="list-disc list-inside space-y-1 ml-4">
                <li>Timestamp of request</li>
                <li>API endpoint called (/sign or /verify)</li>
                <li>API key used (hashed)</li>
                <li>Request IP address</li>
                <li>Success or error status</li>
              </ul>

              <h3 className="text-lg font-semibold text-neutral-900 mt-4">2.3 Cryptographic Data</h3>
              <p>We store:</p>
              <ul className="list-disc list-inside space-y-1 ml-4">
                <li>SHA-256 hashes of signed text (irreversible)</li>
                <li>Ed25519 signatures</li>
                <li>Signed manifests (metadata only)</li>
                <li>Manifest creation timestamp</li>
              </ul>

              <h3 className="text-lg font-semibold text-neutral-900 mt-4">2.4 Payment Information</h3>
              <p>Payment processing is handled by Stripe. We do not store credit card numbers. Stripe provides us with:</p>
              <ul className="list-disc list-inside space-y-1 ml-4">
                <li>Last 4 digits of card</li>
                <li>Card brand (Visa, Mastercard, etc.)</li>
                <li>Billing email</li>
                <li>Payment status (successful, failed, etc.)</li>
              </ul>
            </div>
          </section>

          {/* How We Use Information */}
          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">3. How We Use Your Information</h2>
            <div className="text-neutral-600 space-y-2">
              <p>We use collected information to:</p>
              <ul className="list-disc list-inside space-y-1 ml-4">
                <li>Provide and maintain the Service</li>
                <li>Authenticate API requests</li>
                <li>Generate and verify cryptographic signatures</li>
                <li>Process payments and manage subscriptions</li>
                <li>Send service notifications (quota warnings, billing alerts)</li>
                <li>Respond to support requests</li>
                <li>Detect and prevent fraud or abuse</li>
                <li>Comply with legal obligations</li>
              </ul>
            </div>
          </section>

          {/* What We Never Store */}
          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">4. What We Never Store</h2>
            <div className="bg-primary-light border border-primary p-6 rounded-lg">
              <p className="text-neutral-900 font-semibold mb-2">Provenix is designed with privacy by default:</p>
              <ul className="list-disc list-inside space-y-1 ml-4 text-neutral-700">
                <li><strong>Raw text content:</strong> We never store the text you sign. Only irreversible SHA-256 hashes.</li>
                <li><strong>Plain-text passwords:</strong> All passwords are hashed using bcrypt before storage.</li>
                <li><strong>Plain-text API keys:</strong> API keys are hashed immediately after generation.</li>
                <li><strong>Credit card numbers:</strong> Payment processing is handled entirely by Stripe.</li>
              </ul>
            </div>
          </section>

          {/* Data Retention */}
          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">5. Data Retention</h2>
            <div className="text-neutral-600 space-y-2">
              <p><strong>Manifests:</strong> Stored indefinitely by default to enable long-term verification. You can delete manifests at any time from your dashboard.</p>
              <p><strong>Account data:</strong> Retained for the lifetime of your account. Deleted 90 days after account closure.</p>
              <p><strong>Usage logs:</strong> Retained for 12 months for billing and abuse detection.</p>
              <p><strong>Payment records:</strong> Retained for 7 years to comply with tax and accounting regulations.</p>
            </div>
          </section>

          {/* Security */}
          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">6. Security</h2>
            <div className="text-neutral-600 space-y-2">
              <p>We implement industry-standard security measures:</p>
              <ul className="list-disc list-inside space-y-1 ml-4">
                <li>TLS 1.3 encryption for all data in transit</li>
                <li>AES-256 encryption for data at rest</li>
                <li>Bcrypt password hashing with per-user salts</li>
                <li>Ed25519 private keys stored in Hardware Security Modules (HSMs)</li>
                <li>Regular security audits and penetration testing</li>
                <li>SOC 2 Type II certification (in progress)</li>
              </ul>
            </div>
          </section>

          {/* GDPR Rights */}
          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">7. Your Rights (GDPR)</h2>
            <div className="text-neutral-600 space-y-2">
              <p>If you are in the EU/EEA, you have the following rights:</p>
              <ul className="list-disc list-inside space-y-1 ml-4">
                <li><strong>Right to access:</strong> Request a copy of your personal data.</li>
                <li><strong>Right to rectification:</strong> Correct inaccurate data.</li>
                <li><strong>Right to erasure:</strong> Request deletion of your data (subject to legal retention requirements).</li>
                <li><strong>Right to restriction:</strong> Limit how we process your data.</li>
                <li><strong>Right to data portability:</strong> Receive your data in a machine-readable format.</li>
                <li><strong>Right to object:</strong> Object to processing based on legitimate interests.</li>
              </ul>
              <p className="mt-4">To exercise these rights, contact us at <a href="mailto:privacy@provenix.dev" className="text-primary hover:text-primary-hover">privacy@provenix.dev</a>.</p>
            </div>
          </section>

          {/* Cookies */}
          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">8. Cookies</h2>
            <div className="text-neutral-600 space-y-2">
              <p>We use strictly necessary cookies to:</p>
              <ul className="list-disc list-inside space-y-1 ml-4">
                <li>Maintain authentication sessions</li>
                <li>Prevent CSRF attacks</li>
              </ul>
              <p>We do not use tracking or advertising cookies. See our <a href="/cookie-policy" className="text-primary hover:text-primary-hover">Cookie Policy</a> for details.</p>
            </div>
          </section>

          {/* Third-Party Services */}
          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">9. Third-Party Services</h2>
            <div className="text-neutral-600 space-y-2">
              <p>We use the following third-party processors:</p>
              <ul className="list-disc list-inside space-y-1 ml-4">
                <li><strong>Stripe:</strong> Payment processing (see Stripe's privacy policy)</li>
                <li><strong>Railway:</strong> API hosting (data stored in US/EU regions)</li>
                <li><strong>Vercel:</strong> Dashboard and demo hosting</li>
              </ul>
              <p>All processors are GDPR-compliant and covered by Data Processing Agreements.</p>
            </div>
          </section>

          {/* Changes to Privacy Policy */}
          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">10. Changes to This Policy</h2>
            <div className="text-neutral-600 space-y-2">
              <p>We may update this Privacy Policy from time to time. We will notify you of material changes via email or a notice in your dashboard. Your continued use of the Service after changes constitutes acceptance.</p>
            </div>
          </section>

          {/* Contact */}
          <section>
            <h2 className="text-2xl font-semibold text-neutral-900 mb-4">11. Contact Us</h2>
            <div className="text-neutral-600 space-y-2">
              <p>For privacy-related questions or requests:</p>
              <p><strong>Email:</strong> <a href="mailto:privacy@provenix.dev" className="text-primary hover:text-primary-hover">privacy@provenix.dev</a></p>
              <p><strong>Address:</strong> Provenix Pty Ltd, Perth, Western Australia [full address pending ABN registration]</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  )
}
